FROM node:20-alpine

WORKDIR /app

COPY ./dodolist/package.json ./
COPY ./dodolist/package-lock.json* ./

RUN npm ci

COPY ./dodolist/ ./

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
