export const colors = [
  {
    name: "Taupe",
    value: "bg-stone-400",
    light: "bg-stone-50",
    border: "border-stone-200",
    text: "text-stone-700",
    dark: "bg-gradient-to-br from-stone-500 to-stone-700",
    darkText: "text-stone-50",
    texture: "bg-stone-400/10",
  },
  {
    name: "Olive",
    value: "bg-emerald-600",
    light: "bg-emerald-50",
    border: "border-emerald-300",
    text: "text-emerald-800",
    dark: "bg-gradient-to-br from-emerald-700 to-emerald-900",
    darkText: "text-emerald-50",
    texture: "bg-emerald-600/10",
  },
  {
    name: "Sand",
    value: "bg-amber-300",
    light: "bg-amber-50",
    border: "border-amber-200",
    text: "text-amber-700",
    dark: "bg-gradient-to-br from-amber-400 to-amber-600",
    darkText: "text-amber-50",
    texture: "bg-amber-300/10",
  },
  {
    name: "Clay",
    value: "bg-orange-300",
    light: "bg-orange-50",
    border: "border-orange-200",
    text: "text-orange-700",
    dark: "bg-gradient-to-br from-orange-400 to-orange-600",
    darkText: "text-orange-50",
    texture: "bg-orange-300/10",
  },
  {
    name: "Stone",
    value: "bg-blue-400",
    light: "bg-blue-50",
    border: "border-blue-200",
    text: "text-blue-800",
    dark: "bg-gradient-to-br from-blue-500 to-blue-700",
    darkText: "text-blue-50",
    texture: "bg-blue-400/10",
  },
  {
    name: "Moss",
    value: "bg-lime-400",
    light: "bg-lime-50",
    border: "border-lime-200",
    text: "text-lime-700",
    dark: "bg-gradient-to-br from-lime-500 to-lime-700",
    darkText: "text-lime-50",
    texture: "bg-lime-400/10",
  },
  {
    name: "Slate",
    value: "bg-slate-500",
    light: "bg-slate-50",
    border: "border-slate-200",
    text: "text-slate-700",
    dark: "bg-gradient-to-br from-slate-600 to-slate-800",
    darkText: "text-slate-50",
    texture: "bg-slate-500/10",
  },
  {
    name: "Terracotta",
    value: "bg-rose-400",
    light: "bg-rose-50",
    border: "border-rose-200",
    text: "text-rose-700",
    dark: "bg-gradient-to-br from-rose-500 to-rose-700",
    darkText: "text-rose-50",
    texture: "bg-rose-400/10",
  },
];
