export interface Todo {
  id: string;
  text: string;
  description?: string;
  completed: boolean;
  createdAt: Date;
  completedAt?: Date;
  deadline?: Date;
  reminder?: Date;
  recurring?: "none" | "daily" | "weekly" | "monthly";
  listId: string;
}

export interface UserProfile {
  id: string;
  email: string;
  username: string;
  name?: string;
  verified: boolean;
  avatar?: string;
}

export interface PocketBaseTaskListRecord {
  id?: string; // Optional, autogenerated if not set
  user_id: string; // Required, relation record id
  createdAt: string; // Required
  yjsUpdate?: string; // Optional, plain text value
  yjsClientId?: string; // Optional, plain text value
}

export interface TodoList {
  id: string;
  user_id: string;
  name: string;
  color: string;
  createdAt: string;
  pinned?: boolean;
  archived?: boolean;
  yjsUpdate?: string;
  deleted?: boolean;
}

export interface TodoListWithTodos extends TodoList {
  todos: Todo[];
}